[package]
name = "producerid-service"
version = "0.1.0"
authors = ["Vincent Rischmann <vincent@rischmann.fr>"]

[dependencies]
tiny_http = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.5"
redis = "0.9"
chrono = { version = "0.4", features = ["serde"] }
